@extends('layouts.master')

@section('title', 'Course Revenue Report')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-4">
    <div>
        <h2 class="mb-0 fw-bold">Course Revenue Report</h2>
        <small class="text-muted">Display total revenue generated by each course.</small>
    </div>
    <div class="no-print">
        <button class="btn btn-outline-primary" onclick="window.print()"><i class="bi bi-printer"></i> Print</button>
        <a href="{{ route('reports.index') }}" class="btn btn-outline-secondary"><i class="bi bi-arrow-left"></i> Back</a>
    </div>
</div>

<div class="card border-0 shadow-sm rounded-4 mb-4">
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead class="table-light">
                    <tr>
                        <th class="ps-4">Course</th>
                        <th class="text-center">Number of Students</th>
                        <th class="text-end pe-4">Total Revenue (KES)</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($courseRevenues as $cr)
                        <tr>
                            <td class="ps-4 fw-bold">{{ $cr->course }}</td>
                            <td class="text-center">{{ $cr->number_of_students }}</td>
                            <td class="text-end pe-4 text-success fw-bold">{{ number_format($cr->total_revenue, 2) }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="3" class="text-center py-4 text-muted">No course revenue data found.</td>
                        </tr>
                    @endforelse
                </tbody>
                <tfoot class="table-light fw-bold">
                    <tr>
                        <td colspan="2" class="text-end text-uppercase">Grand Total Revenue:</td>
                        <td class="text-end pe-4 fs-5 text-primary">KES {{ number_format($grandTotal, 2) }}</td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

@endsection

@push('styles')
<style>
    @media print {
        body * { visibility: hidden; }
        .card, .card * { visibility: visible; }
        .no-print { display: none !important; }
        .card { position: absolute; left: 0; top: 0; width: 100%; box-shadow: none !important; }
    }
</style>
@endpush
